apiVersion: v1
kind: Service
metadata:
  name: aleph
  labels:
    app: aleph
spec:
  ports:
    - name: http-aleph 
      port: 80
      protocol: TCP
      targetPort: 80
    - name: prometheus
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
      app: aleph
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aleph
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aleph
        version: v02
    spec:
      containers:
      - name: aleph
        image: otomato/istio-games-aleph:0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
