---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aleph-buggy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: aleph
        version: v03
    spec:
      containers:
      - name: aleph
        image: otomato/istio-games-aleph:buggy
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: otomato.link/v1alpha1
kind: BirdWatch
metadata:
  name: aleph
spec:
  canary_version: v03
  if_unhealthy: rollback
  increment: 1
  interval: 5
#  metric: 'avg_over_time(flask_request_count{http_status="500",job="aleph", endpoint="/version"}[5m])'
  metric: sum(irate(istio_requests_total{destination_service_name="aleph",destination_version="v03",response_code="500"}[30s]))
  service: aleph
  deviation: 0.5
