---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aleph-v04
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: aleph
        version: v04
    spec:
      containers:
      - name: aleph
        image: otomato/istio-games-aleph:0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: otomato.link/v1alpha1
kind: BirdWatch
metadata:
  name: aleph
spec:
  canary_version: v04
  if_unhealthy: freeze
  increment: 5
  interval: 2
  metric: sum(irate(istio_requests_total{destination_service_name="aleph",destination_version="v04",response_code="500"}[30s]))
  service: aleph
  deviation: 1
