---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: beth-laggy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: beth
        version: v04
    spec:
      containers:
      - name: beth
        image: otomato/istio-games-beth:laggy
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: otomato.link/v1alpha1
kind: BirdWatch
metadata:
  name: beth
spec:
  canary_version: v04
  if_unhealthy: rollback
  increment: 2
  metric: 'irate(istio_request_duration_seconds_sum{destination_service_name="beth",destination_version="v04"}[30s])'
  service: beth
  deviation: 30
